In [ ]:
import math
class matrix:
    def __init__(self, size):
        self.matrix = [[0 for i in range(size)] for j in range(size)]
        self.size = size
        self.power = math.ceil(math.log2(size))
        self.parityBits = [0 for i in range(self.power)]
        for i in range(size):
            for j in range(size):
                self.matrix[i][j] = 0
    
    def updateParityBits(self):
        for i in range(self.size):
            for j in range(self.size):
                if self.matrix[i][j] == 1:
                    self.parityBits.append((i,j))
    
    def __str__(self):
        

In [24]:
import numpy as np
from pyldpc import make_ldpc, decode, get_message, encode
from matplotlib import pyplot as plt

n = 72
d_v = 2
d_c = 18
seed = np.random.RandomState(42)
H, G = make_ldpc(n, d_v, d_c, seed=seed, systematic=True, sparse=True)
# print(H)

column_vectors = np.transpose(H)
# print(column_vectors)

collection = {}
for i in range(len(column_vectors)):
    collection[tuple(column_vectors[i])] = collection.get(tuple(column_vectors[i]), []) + [i]
    
for key in collection:
    print(key, collection[key])


(1, 0, 0, 0, 0, 1, 0, 0) [0, 4, 8, 11, 67]
(1, 0, 0, 0, 1, 0, 0, 0) [1, 5, 7, 29, 47, 65]
(1, 0, 0, 0, 0, 0, 0, 1) [2, 9, 66]
(1, 0, 0, 0, 0, 0, 1, 0) [3, 6, 10, 68]
(0, 1, 0, 0, 0, 0, 1, 0) [12, 16, 20, 22, 27]
(0, 1, 0, 0, 0, 0, 0, 1) [13, 17, 19, 23, 25]
(0, 1, 0, 0, 1, 0, 0, 0) [14, 18, 28]
(0, 1, 0, 0, 0, 1, 0, 0) [15, 21, 24, 26, 69]
(0, 0, 1, 0, 1, 0, 0, 0) [30, 31, 33, 35, 40]
(0, 0, 1, 0, 0, 0, 1, 0) [32, 36, 38, 42, 44]
(0, 0, 1, 0, 0, 0, 0, 1) [34, 37, 39, 46, 70]
(0, 0, 1, 0, 0, 1, 0, 0) [41, 43, 45]
(0, 0, 0, 1, 1, 0, 0, 0) [48, 56, 59, 63]
(0, 0, 0, 1, 0, 1, 0, 0) [49, 53, 58, 60, 61]
(0, 0, 0, 1, 0, 0, 0, 1) [50, 51, 55, 62, 71]
(0, 0, 0, 1, 0, 0, 1, 0) [52, 54, 57, 64]


In [15]:
np.set_printoptions(threshold=np.inf)
print(G)


[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [20]:
import numpy as np
from pyldpc import make_ldpc, decode, get_message, encode
from matplotlib import pyplot as plt

n = 6
d_v = 2
d_c = 3
seed = np.random.RandomState(42)
H, G = make_ldpc(n, d_v, d_c, seed=seed, systematic=True, sparse=True)
print(H)

[[1 0 0 1 1 0]
 [0 1 1 0 0 1]
 [1 0 0 1 0 1]
 [0 1 1 0 1 0]]
